name = "cf_ai_currency_helper"
main = "src/worker.mjs"
compatibility_date = "2025-10-27"

# Bind Workers AI
[ai]
binding = "AI"

# Durable object for session memory
[durable_objects]
bindings = [{ name = "SESSIONS", class_name = "SessionDO" }]

[[migrations]]
tag = "v1"
new_classes = ["SessionDO"]

# Serve the frontend from /public during dev
[assets]
directory = "src/public"